## 0. Obsługa jupyter notebook

#### edycja - podświetlenie zielone
`shift` + `enter` - wywołanie komórki i przejście do kolejnej (stworzenie kolejnej)

`ctrl` + `enter` = wywołanie komórki

#### wybór - podświetlenie niebieskie
`A` - stworzenie komórki nad obecną komórką (Above)

`B` - stworzenie komórski pod obecną komórką (Below)

`D` + `D` - usunięcie podświetlonej komórki

#### typ komórki
`ctrl` + `M` - code > markdown 

`ctrl` + `Y` - markdown > code 


#### gdy nie wiemy jak działa dana funkcja w biblitece
`shift` + `tab` - wyświetlenie dokumentacji (DocString)


# 1. NumPy 

In [1]:
import numpy as np

## 1.1 Typy danych w tablicach numpy 

In [2]:
# lista
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [3]:
# lista array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
# typ listy zależny od tego co wrzucimy do listy 
a.dtype

dtype('int32')

`dtype` - typ skalarów w liście

In [7]:
np.array([1, 2, 3, 4, 5], dtype = "float32")

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
np.array([1, 2, 3, 4, 5], dtype = "str") # zwraca unicode

array(['1', '2', '3', '4', '5'], dtype='<U1')

hierarchia dtype

In [9]:
# co się stanie jak float znajdzie się w liście intów?
np.array([1, 2, 3.14, 2.9123412312], dtype = "int64")

array([1, 2, 3, 2], dtype=int64)

In [12]:
# co się stanie jak napis znajdzie się w liście intów?
np.array([1, 2, 3, "słoń"], dtype=int64)

NameError: name 'int64' is not defined

## 1.2 Tworzenie tablic w numpy

In [13]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
[i for i in range(3, 10, 2)]

[3, 5, 7, 9]

In [17]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [18]:
# lista zer
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# lista jedynek
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
# repeat
np.repeat(3, 5)

array([3, 3, 3, 3, 3])

In [21]:
np.repeat([3, 4], 4)

array([3, 3, 3, 3, 4, 4, 4, 4])

In [22]:
np.array([3, 4]).repeat(2).repeat(2)

array([3, 3, 3, 3, 4, 4, 4, 4])

In [23]:
np.array([3, 4]).repeat([1,3])

array([3, 4, 4, 4])

In [24]:
# bardziej intuicyjne
np.tile([3, 4], 3)

array([3, 4, 3, 4, 3, 4])

# 1.3 ndarray - wielowymiarowość

In [25]:
a = [[1, 2, 3],
     [1, 2, 3]]

b = np.array(a)
b

array([[1, 2, 3],
       [1, 2, 3]])

In [26]:
# wymiar
b.ndim

2

In [27]:
# ksztalt - ile wierszy, kolumn
b.shape

(2, 3)

In [28]:
c = np.ones(24, dtype = "int32")

In [29]:
c

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [30]:
c.shape

(24,)

In [31]:
c.reshape(24, 1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [32]:
c.reshape(4, 6)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

**Uwaga!** możemy wykonywać `reshape` dopóki `shape` pomieści dokładnie tyle danych ile elementów ma pierwotna lista.

In [33]:
c.reshape(4, 5)

ValueError: cannot reshape array of size 24 into shape (4,5)

In [34]:
# do jednego wymiaru
d = c.flatten()
d

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [35]:
d.reshape(4, 3, 2) # lista mająca 4 listy, które mają 3 listy po 2 elementy

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

# 1.4 Indeksowanie

In [36]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
a[2]

array([10, 11, 12, 13, 14])

In [38]:
a[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
a[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [40]:
a[:, 1:5]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [41]:
a > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [42]:
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
(a > 3) and (a < 10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
a > 3 & a < 10

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [45]:
(a > 3) & (a < 10)

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [46]:
a[(a > 3) & (a < 10)]

array([4, 5, 6, 7, 8, 9])

In [47]:
a[(a > 3) | (a < 10)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
# szukanie indeksów
index = np.where((a > 3) & (a < 10))
index
# krotka, pierwsza lista wskazuje wiersz, druga lista wskazuje kolumny

(array([0, 1, 1, 1, 1, 1], dtype=int64),
 array([4, 0, 1, 2, 3, 4], dtype=int64))

## 1.5 Zadanie 1

1. Stwórz macierz 1)
2. Spróbuj indeksami dostać się do elementów zaznaczonych na czerwono 2), 3), 4) 
3. Znajdź indeksy wartości mniejszych niż 10, ale większych od 4

![](img/Zadanie1.png)

In [49]:
A = np.arange(1, 16).reshape([3,5])

In [50]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [51]:
A[1]

array([ 6,  7,  8,  9, 10])

In [52]:
A[:, 3]

array([ 4,  9, 14])

In [53]:
A[1:, 3:]

array([[ 9, 10],
       [14, 15]])

In [54]:
np.where((A > 4) & (A < 10))

(array([0, 1, 1, 1, 1], dtype=int64), array([4, 0, 1, 2, 3], dtype=int64))

# 2. Operacje na tablicach

## 2.1 Podstawowe działania

In [55]:
# listy a, b
a = np.array([1, 1, 2, 1])
b = np.array([1, 2, 3, 4])

In [56]:
a + 3
a * 3


array([3, 3, 6, 3])

In [57]:
a + b
a - b
a/b

array([1.        , 0.5       , 0.66666667, 0.25      ])

In [58]:
a = np.arange(5)
b = np.repeat(2, 4)

In [61]:
a + b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [59]:
a

array([0, 1, 2, 3, 4])

In [60]:
b

array([2, 2, 2, 2])

## 2.2 Metody obiektów ndarray

In [62]:
a = np.arange(10, 21)

In [63]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
a.mean()

15.0

In [66]:
a.sum()
a.max()
a.min()

10

In [67]:
a.argmax() # indeks maksymalnej wartości

10

In [68]:
a.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145, 165], dtype=int32)

In [69]:
a.sum(axis = 0)

165

In [70]:
A = np.arange(5*5).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
A.sum()

300

In [72]:
A.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [73]:
A.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [74]:
A.max(axis = 0)
A.min(axis = 1)

array([ 0,  5, 10, 15, 20])

In [75]:
b = np.array([1, -1, 1, -1, 1])

In [76]:
A * b

array([[  0,  -1,   2,  -3,   4],
       [  5,  -6,   7,  -8,   9],
       [ 10, -11,  12, -13,  14],
       [ 15, -16,  17, -18,  19],
       [ 20, -21,  22, -23,  24]])

In [77]:
A * b.reshape(5, 1)

array([[  0,   1,   2,   3,   4],
       [ -5,  -6,  -7,  -8,  -9],
       [ 10,  11,  12,  13,  14],
       [-15, -16, -17, -18, -19],
       [ 20,  21,  22,  23,  24]])

In [78]:
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
A @ B

array([[ 300,  310,  320,  330,  340,  350,  360,  370,  380,  390],
       [ 800,  835,  870,  905,  940,  975, 1010, 1045, 1080, 1115],
       [1300, 1360, 1420, 1480, 1540, 1600, 1660, 1720, 1780, 1840],
       [1800, 1885, 1970, 2055, 2140, 2225, 2310, 2395, 2480, 2565],
       [2300, 2410, 2520, 2630, 2740, 2850, 2960, 3070, 3180, 3290]])

In [80]:
np.dot(A, B)

array([[ 300,  310,  320,  330,  340,  350,  360,  370,  380,  390],
       [ 800,  835,  870,  905,  940,  975, 1010, 1045, 1080, 1115],
       [1300, 1360, 1420, 1480, 1540, 1600, 1660, 1720, 1780, 1840],
       [1800, 1885, 1970, 2055, 2140, 2225, 2310, 2395, 2480, 2565],
       [2300, 2410, 2520, 2630, 2740, 2850, 2960, 3070, 3180, 3290]])

# 2.3 Zadanie 2

Napisz funkcję `dzialanie`, która jako argumenty przyjmuje dwie listy A i B (o wymiarach (20, )), a następnie konwertuje je do macierzy, która ma 4 wiersze i 5 kolumn. W kolejnym kroku na tak powstałych macierzach wykonaj operacje:

1. Kolumna `A` o indeksie 2 jest mnożona przez sumę wiersza `B` o indeksie 3.
2. Kolumna `A` o indeksie 4 jest zamieniona przez kolumnę `B` o indeksie 1 pomnożoną przez -2.
3. Macierz `C` to macierz powstała z kroków 1 i 2.
4. Co druga kolumna macierzy C jest mnożona przez 2.

In [81]:
def dzialanie(A, B):
    A, B = A.reshape(4,5), B.reshape(4,5)
    C = A.copy()
    C[:, 2] *= B[3].sum()
    C[:, 4] = B[:,1]*(-2)
    C[:, ::2] *= 2 
    
    return C

In [82]:
A = np.arange(1, 21)
B = np.arange(20, 40)

dzialanie(A, B)

array([[   2,    2, 1110,    4,  -84],
       [  12,    7, 2960,    9, -104],
       [  22,   12, 4810,   14, -124],
       [  32,   17, 6660,   19, -144]])

In [ ]:
# array([[   2,    2, 1110,    4,  -84],
#        [  12,    7, 2960,    9, -104],
#        [  22,   12, 4810,   14, -124],
#        [  32,   17, 6660,   19, -144]])

# 3. Wprowadzenie do pandas

## 3.1 Podstawy

In [83]:
import pandas as pd

In [84]:
# import danych
df = pd.read_csv("https://raw.githubusercontent.com/R-Ladies-Warsaw/PoweR/master/Cz%C4%99%C5%9B%C4%87%202%20-%20Formatowanie%20danych/Python/data/vgsales.csv",
                delimiter = ",").dropna().reset_index(drop = True)

In [85]:
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16286  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16287  16597                     Men in Black II: Alien Escape       GC   
16288  16598  SCORE International Baja 1000: The Official Game      PS2   
16289  16599                                        Know How 2       DS   
16290  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16286  2002.0      Platform       Kemco      0.01      0.00      0.00   
16287  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16288  2008.0        Racing  Activision      0.00      0.00      0.00   
16289  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16290  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16286         0.00          0.01  
16287         0.00          0.01  
16288         0.00          0.01  
16289         0.00          0.01  
16290         0.00          0.01  

[16291 rows x 11 columns]

In [86]:
type(df)

pandas.core.frame.DataFrame

In [87]:
df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [88]:
df = df.drop(["Rank"], axis = 1)

In [89]:
df

Name Platform    Year  \
0                                            Wii Sports      Wii  2006.0   
1                                     Super Mario Bros.      NES  1985.0   
2                                        Mario Kart Wii      Wii  2008.0   
3                                     Wii Sports Resort      Wii  2009.0   
4                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16286                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16287                     Men in Black II: Alien Escape       GC  2003.0   
16288  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16289                                        Know How 2       DS  2010.0   
16290                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
0            Sports    Nintendo     41.49     29.02      3.77         8.46   
1          Platform    Nintendo     29.08      3.58      6.81         0.77   
2            Racing    Nintendo     15.85     12.88      3.79         3.31   
3            Sports    Nintendo     15.75     11.01      3.28         2.96   
4      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16286      Platform       Kemco      0.01      0.00      0.00         0.00   
16287       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16288        Racing  Activision      0.00      0.00      0.00         0.00   
16289        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16290      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  
0             82.74  
1             40.24  
2             35.82  
3             33.00  
4             31.37  
...             ...  
16286          0.01  
16287          0.01  
16288          0.01  
16289          0.01  
16290          0.01  

[16291 rows x 10 columns]

## 3.1.1 Atrybuty pd.DataFrame

In [90]:
df.index

RangeIndex(start=0, stop=16291, step=1)

In [91]:
type(df.index)

pandas.core.indexes.range.RangeIndex

In [92]:
df.columns

Index(['Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [93]:
df.dtypes

Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [94]:
df.axes

[RangeIndex(start=0, stop=16291, step=1),
 Index(['Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
        'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
       dtype='object')]

In [95]:
df.shape

(16291, 10)

## 3.1.2 Wybieranie kolumn

In [96]:
df["Platform"]

0        Wii
1        NES
2        Wii
3        Wii
4         GB
        ... 
16286    GBA
16287     GC
16288    PS2
16289     DS
16290    GBA
Name: Platform, Length: 16291, dtype: object

In [98]:
df.JP_Sales

0         3.77
1         6.81
2         3.79
3         3.28
4        10.22
         ...  
16286     0.00
16287     0.00
16288     0.00
16289     0.00
16290     0.00
Name: JP_Sales, Length: 16291, dtype: float64

In [97]:
df[["Platform", "Name"]]

Platform                                              Name
0          Wii                                        Wii Sports
1          NES                                 Super Mario Bros.
2          Wii                                    Mario Kart Wii
3          Wii                                 Wii Sports Resort
4           GB                          Pokemon Red/Pokemon Blue
...        ...                                               ...
16286      GBA                Woody Woodpecker in Crazy Castle 5
16287       GC                     Men in Black II: Alien Escape
16288      PS2  SCORE International Baja 1000: The Official Game
16289       DS                                        Know How 2
16290      GBA                                  Spirits & Spells

[16291 rows x 2 columns]

# 3.2 Indeksowanie

Główne sposoby indeksowania:

1. []
2. .iloc[]
3. .loc[]

In [99]:
np.random.seed(123)

In [100]:
smalldf = df.iloc[np.random.randint(0, df.shape[0], 10),:].reset_index(drop = True)

In [101]:
smalldf

Name Platform    Year     Genre  \
0             The Godfather (old US sales)       XB  2006.0    Action   
1  Nobunaga no Yabou Online: Houou no Shou      PS3  2012.0  Strategy   
2         Romance of the Three Kingdoms XI      PS2  2007.0  Strategy   
3                        Sonic Generations     X360  2011.0  Platform   
4                                     Vexx       GC  2003.0  Platform   
5                    Angry Birds Star Wars      Wii  2013.0  Strategy   
6       Saru! Get You! SaruSaru Daisakusen      PSP  2007.0  Platform   
7       Barnyard Blast: Swine of the Night       DS  2008.0  Platform   
8                   God Eater Resurrection      PSV  2015.0    Action   
9                      Star Trek: The Game       PC  2013.0    Action   

                     Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
0              Electronic Arts      0.42      0.11      0.00         0.02   
1                  Ackkstudios      0.00      0.00      0.01         0.00   
2                   Tecmo Koei      0.00      0.00      0.07         0.00   
3                         Sega      0.71      0.57      0.00         0.14   
4        Acclaim Entertainment      0.05      0.01      0.00         0.00   
5                   Activision      0.21      0.10      0.00         0.03   
6  Sony Computer Entertainment      0.00      0.00      0.03         0.00   
7          Big Ben Interactive      0.02      0.00      0.00         0.00   
8           Namco Bandai Games      0.00      0.00      0.19         0.00   
9           Namco Bandai Games      0.00      0.02      0.00         0.00   

   Global_Sales  
0          0.55  
1          0.01  
2          0.07  
3          1.42  
4          0.06  
5          0.35  
6          0.03  
7          0.02  
8          0.19  
9          0.03

### Sposób 1) []

In [102]:
smalldf[1:3] # 

Name Platform    Year     Genre  \
1  Nobunaga no Yabou Online: Houou no Shou      PS3  2012.0  Strategy   
2         Romance of the Three Kingdoms XI      PS2  2007.0  Strategy   

     Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
1  Ackkstudios       0.0       0.0      0.01          0.0          0.01  
2   Tecmo Koei       0.0       0.0      0.07          0.0          0.07

In [103]:
smalldf[0::2] # 

Name Platform    Year     Genre  \
0        The Godfather (old US sales)       XB  2006.0    Action   
2    Romance of the Three Kingdoms XI      PS2  2007.0  Strategy   
4                                Vexx       GC  2003.0  Platform   
6  Saru! Get You! SaruSaru Daisakusen      PSP  2007.0  Platform   
8              God Eater Resurrection      PSV  2015.0    Action   

                     Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
0              Electronic Arts      0.42      0.11      0.00         0.02   
2                   Tecmo Koei      0.00      0.00      0.07         0.00   
4        Acclaim Entertainment      0.05      0.01      0.00         0.00   
6  Sony Computer Entertainment      0.00      0.00      0.03         0.00   
8           Namco Bandai Games      0.00      0.00      0.19         0.00   

   Global_Sales  
0          0.55  
2          0.07  
4          0.06  
6          0.03  
8          0.19

In [104]:
# nie można łączyć
smalldf[0:4, 1]

TypeError: '(slice(0, 4, None), 1)' is an invalid key

### Sposób 2) .loc[]

In [105]:
smalldf.loc[0:4, ["Name", "Platform"]]

Name Platform
0             The Godfather (old US sales)       XB
1  Nobunaga no Yabou Online: Houou no Shou      PS3
2         Romance of the Three Kingdoms XI      PS2
3                        Sonic Generations     X360
4                                     Vexx       GC

In [106]:
smalldf.loc[0:4, smalldf.columns[0:4]]

Name Platform    Year     Genre
0             The Godfather (old US sales)       XB  2006.0    Action
1  Nobunaga no Yabou Online: Houou no Shou      PS3  2012.0  Strategy
2         Romance of the Three Kingdoms XI      PS2  2007.0  Strategy
3                        Sonic Generations     X360  2011.0  Platform
4                                     Vexx       GC  2003.0  Platform

In [107]:
smalldf.loc[smalldf.Global_Sales > 1]

Name Platform    Year     Genre Publisher  NA_Sales  EU_Sales  \
3  Sonic Generations     X360  2011.0  Platform      Sega      0.71      0.57   

   JP_Sales  Other_Sales  Global_Sales  
3       0.0         0.14          1.42

In [108]:
smalldf.loc[(smalldf.Genre == "Platform") & (smalldf.Year < 2010)]

Name Platform    Year     Genre  \
4                                Vexx       GC  2003.0  Platform   
6  Saru! Get You! SaruSaru Daisakusen      PSP  2007.0  Platform   
7  Barnyard Blast: Swine of the Night       DS  2008.0  Platform   

                     Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
4        Acclaim Entertainment      0.05      0.01      0.00          0.0   
6  Sony Computer Entertainment      0.00      0.00      0.03          0.0   
7          Big Ben Interactive      0.02      0.00      0.00          0.0   

   Global_Sales  
4          0.06  
6          0.03  
7          0.02

### Sposób 3) .iloc[]

In [109]:
smalldf.iloc[0:3, 3:5]

Genre        Publisher
0    Action  Electronic Arts
1  Strategy      Ackkstudios
2  Strategy       Tecmo Koei

In [110]:
smalldf.iloc[[0, 1, 2], [3, 4]]

Genre        Publisher
0    Action  Electronic Arts
1  Strategy      Ackkstudios
2  Strategy       Tecmo Koei

In [111]:
smalldf.iloc[2:10:3, 2:10:2]

Year           Publisher  EU_Sales  Other_Sales
2  2007.0          Tecmo Koei       0.0         0.00
5  2013.0          Activision       0.1         0.03
8  2015.0  Namco Bandai Games       0.0         0.00

**Komentarz:**

- gdy chcemy kolumnę po nazwie - []
- gdy chcemy obserwacje, kolumny po wartościach logicznych lub ich nazwach - .loc[]
- gdy chcemy obserwacje, kolumny po ich indeksach - .iloc[]

# 3.3 Metody ramki danych

In [112]:
df.Name

0                                              Wii Sports
1                                       Super Mario Bros.
2                                          Mario Kart Wii
3                                       Wii Sports Resort
4                                Pokemon Red/Pokemon Blue
                               ...                       
16286                  Woody Woodpecker in Crazy Castle 5
16287                       Men in Black II: Alien Escape
16288    SCORE International Baja 1000: The Official Game
16289                                          Know How 2
16290                                    Spirits & Spells
Name: Name, Length: 16291, dtype: object

In [113]:
df.Name.count()

16291

In [114]:
df.Name.unique()

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii', ...,
       'Plushees', 'Woody Woodpecker in Crazy Castle 5', 'Know How 2'],
      dtype=object)

In [115]:
df.Name.unique()
df.Name.unique().shape

(11325,)

In [116]:
df.Year.mode()
df.Global_Sales.median()
df.Global_Sales.max()

82.74

In [117]:
df.describe()

Year      NA_Sales      EU_Sales      JP_Sales   Other_Sales  \
count  16291.000000  16291.000000  16291.000000  16291.000000  16291.000000   
mean    2006.405561      0.265647      0.147731      0.078833      0.048426   
std        5.832412      0.822432      0.509303      0.311879      0.190083   
min     1980.000000      0.000000      0.000000      0.000000      0.000000   
25%     2003.000000      0.000000      0.000000      0.000000      0.000000   
50%     2007.000000      0.080000      0.020000      0.000000      0.010000   
75%     2010.000000      0.240000      0.110000      0.040000      0.040000   
max     2020.000000     41.490000     29.020000     10.220000     10.570000   

       Global_Sales  
count  16291.000000  
mean       0.540910  
std        1.567345  
min        0.010000  
25%        0.060000  
50%        0.170000  
75%        0.480000  
max       82.740000

In [119]:
# ile gier sprzedało się w nakładzie większym niż 1 mln
df.loc[df.Global_Sales > 1].shape[0]

2031

In [120]:
# jaki procent wszystkich gier
df.Global_Sales[df.Global_Sales > 1].count()/df.Global_Sales.count()*100

12.467006322509361

In [121]:
year_min = df.Year.argmin()
year_min

257

In [122]:
df.Year[year_min]

1980.0

In [123]:
df.NA_Sales + df.EU_Sales

0        70.51
1        32.66
2        28.73
3        26.76
4        20.16
         ...  
16286     0.01
16287     0.01
16288     0.00
16289     0.01
16290     0.01
Length: 16291, dtype: float64

In [124]:
df.EU_Sales.sort_values(ascending = False)

0        29.02
2        12.88
3        11.01
10       11.00
16        9.27
         ...  
10308     0.00
10306     0.00
10303     0.00
10297     0.00
8145      0.00
Name: EU_Sales, Length: 16291, dtype: float64

In [125]:
df.EU_Sales.sort_values(ascending = False).head()

0     29.02
2     12.88
3     11.01
10    11.00
16     9.27
Name: EU_Sales, dtype: float64

In [126]:
df.EU_Sales.sort_values(ascending = False).reset_index().head()

index  EU_Sales
0      0     29.02
1      2     12.88
2      3     11.01
3     10     11.00
4     16      9.27

In [127]:
df.EU_Sales.sort_values(ascending = False).reset_index(drop = True).head()

0    29.02
1    12.88
2    11.01
3    11.00
4     9.27
Name: EU_Sales, dtype: float64

In [128]:
df.sort_values(["Genre", "Platform"]).reset_index(drop = True).head()

Name Platform    Year   Genre  \
0                      Frogger     2600  1981.0  Action   
1  E.T.: The Extra Terrestrial     2600  1981.0  Action   
2                   Spider-Man     2600  1981.0  Action   
3             Custer's Revenge     2600  1981.0  Action   
4                        Alien     2600  1981.0  Action   

                      Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
0                  Parker Bros.      2.06      0.12       0.0         0.02   
1                         Atari      1.84      0.11       0.0         0.02   
2                  Parker Bros.      0.87      0.05       0.0         0.01   
3                      Mystique      0.76      0.05       0.0         0.01   
4  20th Century Fox Video Games      0.74      0.04       0.0         0.01   

   Global_Sales  
0          2.20  
1          1.97  
2          0.93  
3          0.82  
4          0.79

# 3.4 Zadanie 3

Wybierz gry, które sprzedały się lepiej w Europie niż w Ameryce Północnej. Ile ich było? Jaki to procent wszystkich gier?

# 3.5 groupby & merge

In [ ]:
df.groupby("Genre")

In [ ]:
df.groupby("Genre").Name

In [ ]:
df.groupby("Genre")[["Name", "Global_Sales"]]

In [ ]:
df.groupby("Genre").Name.agg("count")

In [ ]:
df.groupby("Genre").Global_Sales.agg("sum")

In [ ]:
df2 = df.groupby(["Genre", "Platform"])[["Global_Sales", "Name"]].agg("max")

In [ ]:
df2

In [ ]:
df3 = df.groupby("Platform").Global_Sales.agg("sum")

In [ ]:
df3 = df3.to_frame()
df3 = df3.reset_index()

In [ ]:
df3.head()

In [ ]:
df4 = df.merge(df3, on = "Platform")

In [ ]:
df4 = df4.rename(columns = {'Global_Sales_y' : "Platform_Global_Sales",
                     'Global_Sales_x' : "Global_Sales"})

In [ ]:
df4.head()

# 3.6 Zadanie 4

Które gry sprzedały się najlepiej w swojej kategorii?

# 3.7 Zadanie 5

Jaka była sprzedarz gier na konsolę w 2 roku ich sprzedaży. Pokaż tylko te konsole, w których sprzedaż w 2 roku była mniejsza niż w 1.

# pandas.plot

Doc: 

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html
- https://pandas.pydata.org/docs/user_guide/visualization.html

In [ ]:
df.head()

In [ ]:
df.plot(x = "EU_Sales", y = "NA_Sales", kind = "scatter", alpha = 0.5)

In [ ]:
df.groupby("Genre").size().plot.bar()

In [ ]:
df.loc[:, ["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].plot.box(logy = True)

In [ ]:
[df.Genre.nunique(), df.Platform.nunique()]

In [ ]:
df.groupby(["Year"]).agg({"Global_Sales": "sum", "Name": "count"}).\
    plot.line(subplots = True, legend = False, figsize = (10, 6), title = "Global sales vs number of games per year")